"""内置 Tool Call 清单（供「工具」页展示；与路由/服务实际能力对齐）。"""
from __future__ import annotations

from typing import Any, Dict, List


def list_builtin_tools() -> List[Dict[str, Any]]:
    return [
        {
            "id": "tool_link_pipeline",
            "name": "链接转写流水线",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "提交视频/图文链接，服务端执行下载、转写、摘要与 Markdown/HTML 产出。",
            "inputs": [
                {"name": "platform", "type": "string", "required": True, "hint": "抖音 / B站 / 小红书等"},
                {"name": "link", "type": "string", "required": True, "hint": "可下载或可解析的页面 URL"},
            ],
            "outputs": "任务进入队列；SSE 日志与最终 MD/HTML 路径由任务状态接口返回。",
        },
        {
            "id": "tool_xhs_user_search",
            "name": "小红书用户搜索与画像",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "通过小红书号（数字 ID）搜索用户主页，解析 profile URL 并自动启动画像分析流水线。内部通过浏览器自动化（CDP/Playwright）完成 red_id → creator_id → profile_url 的解析。",
            "inputs": [
                {"name": "red_id", "type": "string", "required": True, "hint": "小红书号（纯数字 ID，如 9545679835）"},
                {"name": "user_prompt", "type": "string", "required": False, "hint": "额外分析指令，如「做用户画像」「分析内容风格」"},
            ],
            "outputs": "解析结果（creator_id、display_name、profile_url）与流水线任务 ID。",
        },
        {
            "id": "tool_rag_index",
            "name": "RAG 索引与库管理",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "向量库文件入库、库切换、切片与 metadata 配置（kb / rag_libraries）。",
            "inputs": [
                {"name": "path", "type": "string", "required": False, "hint": "服务端白名单路径或上传后的路径"},
                {"name": "library_id", "type": "string", "required": False, "hint": "目标向量库 ID"},
            ],
            "outputs": "索引任务结果 JSON（成功条数、错误信息等，以具体 API 为准）。",
        },
        {
            "id": "tool_rag_search",
            "name": "RAG 语义检索",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "在已连接 Milvus 与当前库上执行语义检索（与 kb_search 对齐）。",
            "inputs": [
                {"name": "query", "type": "string", "required": True, "hint": "自然语言检索句"},
                {"name": "top_k", "type": "int", "required": False, "hint": "返回条数，默认由服务端配置"},
            ],
            "outputs": "命中文本片段列表（含 score、路径、切片内容摘要）。",
        },
        {
            "id": "tool_doc_analyze",
            "name": "多模态文档解析",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "服务端路径或上传文件：DocumentProcessor / MinerU 等解析链路。",
            "inputs": [
                {"name": "path", "type": "string", "required": True, "hint": "服务端可读绝对路径"},
            ],
            "outputs": "解析状态、文本长度、文档类型与错误信息（若有）。",
        },
        {
            "id": "tool_cache_rw",
            "name": "Redis 中间缓存",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "查询、更新或导出任务中间产物缓存条目。",
            "inputs": [
                {"name": "task_key", "type": "string", "required": False, "hint": "按任务键过滤"},
                {"name": "artifact", "type": "string", "required": False, "hint": "按产物类型过滤"},
            ],
            "outputs": "缓存行 JSON 或导出文件路径（取决于 API）。",
        },
        {
            "id": "tool_ops_snapshot",
            "name": "OPS 观测",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "调用统计、事件流与运维建议摘要。",
            "inputs": [],
            "outputs": "overview JSON（调用量、Top 路径、事件列表等）。",
        },
        {
            "id": "tool_comment_scraper",
            "name": "评论区抓取",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "mcp",
            "mcp_server": "comment-scraper",
            "description": "抓取社交媒体平台评论区。支持小红书/B站/抖音。返回结构化评论（作者、正文、时间、属地、点赞、回复链）。",
            "inputs": [
                {"name": "url", "type": "string", "required": True, "hint": "目标链接（小红书需带 xsec_token）"},
                {"name": "platform", "type": "string", "required": False, "hint": "xiaohongshu / bilibili / douyin，空则自动检测"},
                {"name": "max_count", "type": "int", "required": False, "hint": "最多抓取条数，默认不限制"},
            ],
            "outputs": "评论文本（含序号、作者、时间、属地、点赞数、回复链）。",
        },
        {
            "id": "tool_rss_reader",
            "name": "RSS 订阅阅读",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "读取当前用户在 RSS 阅读器中的订阅文章（标题、摘要、链接、已读/星标）。",
            "inputs": [
                {"name": "query", "type": "string", "required": False, "hint": "标题/摘要关键词过滤"},
                {"name": "limit", "type": "int", "required": False, "hint": "返回条数，默认 10"},
                {"name": "unread_only", "type": "bool", "required": False, "hint": "仅未读"},
                {"name": "starred_only", "type": "bool", "required": False, "hint": "仅星标"},
            ],
            "outputs": "JSON：items 列表与 stats 统计。",
        },
        {
            "id": "tool_local_file_list",
            "name": "本地目录列举",
            "kind": "tool_call",
            "version": "1.1.0",
            "impl": "internal",
            "description": "列举白名单目录（一层或 recursive 递归，受 max_depth/limit 限制）。",
            "inputs": [
                {"name": "path", "type": "string", "required": False, "hint": "绝对路径；空则白名单根"},
                {"name": "recursive", "type": "bool", "required": False, "hint": "是否递归"},
                {"name": "max_depth", "type": "int", "required": False, "hint": "递归深度，默认 3"},
                {"name": "limit", "type": "int", "required": False, "hint": "最多返回条目数"},
            ],
            "outputs": "entries 列表（name、path、type、size_bytes）。",
        },
        {
            "id": "tool_local_file_read",
            "name": "本地文件读取",
            "kind": "tool_call",
            "version": "1.1.0",
            "impl": "internal",
            "description": "读取白名单内 UTF-8 文本（支持 offset 行偏移与截断）。",
            "inputs": [
                {"name": "path", "type": "string", "required": True, "hint": "绝对路径"},
                {"name": "limit", "type": "int", "required": False, "hint": "最大字符数"},
                {"name": "offset", "type": "int", "required": False, "hint": "跳过前 N 行"},
            ],
            "outputs": "text、truncated、offset 等 JSON。",
        },
        {
            "id": "tool_local_file_write",
            "name": "本地文件写入",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "写入或追加白名单内文本文件（可自动创建父目录）。",
            "inputs": [
                {"name": "path", "type": "string", "required": True, "hint": "目标绝对路径"},
                {"name": "content", "type": "string", "required": True, "hint": "UTF-8 文本"},
                {"name": "append", "type": "bool", "required": False, "hint": "追加或覆盖"},
            ],
            "outputs": "path、size_bytes、created 等 JSON。",
        },
        {
            "id": "tool_local_file_mkdir",
            "name": "本地目录创建",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "在白名单内创建目录（可递归创建父目录）。",
            "inputs": [
                {"name": "path", "type": "string", "required": True, "hint": "目录绝对路径"},
                {"name": "parents", "type": "bool", "required": False, "hint": "是否创建父目录"},
            ],
            "outputs": "path、created JSON。",
        },
        {
            "id": "tool_local_file_move",
            "name": "本地文件移动",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "移动或重命名白名单内文件/目录。",
            "inputs": [
                {"name": "source", "type": "string", "required": True, "hint": "源路径"},
                {"name": "dest", "type": "string", "required": True, "hint": "目标路径"},
                {"name": "overwrite", "type": "bool", "required": False, "hint": "覆盖已存在目标"},
            ],
            "outputs": "source、dest、moved JSON。",
        },
        {
            "id": "tool_local_file_copy",
            "name": "本地文件复制",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "复制/粘贴白名单内文件或目录树到目标位置。",
            "inputs": [
                {"name": "source", "type": "string", "required": True, "hint": "源路径"},
                {"name": "dest", "type": "string", "required": True, "hint": "目标路径"},
                {"name": "overwrite", "type": "bool", "required": False, "hint": "覆盖目标"},
                {"name": "recursive", "type": "bool", "required": False, "hint": "目录是否递归复制"},
            ],
            "outputs": "source、dest、file_count JSON。",
        },
        {
            "id": "tool_local_file_find",
            "name": "本地文件查找",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "递归 glob 查找：按名称/大小/修改时间过滤，适合大型整理任务。",
            "inputs": [
                {"name": "root", "type": "string", "required": True, "hint": "搜索根目录"},
                {"name": "glob_pattern", "type": "string", "required": False, "hint": "如 *.md、**/*.py"},
                {"name": "name_contains", "type": "string", "required": False, "hint": "名称关键词"},
                {"name": "limit", "type": "int", "required": False, "hint": "最多返回条数"},
            ],
            "outputs": "matches 列表、scanned_files、truncated。",
        },
        {
            "id": "tool_local_file_grep",
            "name": "本地内容 Grep",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "Cursor 式正则 grep：content/files_with_matches/count 三种输出。",
            "inputs": [
                {"name": "pattern", "type": "string", "required": True, "hint": "正则表达式"},
                {"name": "path", "type": "string", "required": False, "hint": "文件或目录；空则搜白名单根"},
                {"name": "glob", "type": "string", "required": False, "hint": "文件名过滤如 *.py"},
                {"name": "output_mode", "type": "string", "required": False, "hint": "content|files_with_matches|count"},
            ],
            "outputs": "matches/files/count、scanned_files。",
        },
        {
            "id": "tool_local_file_info",
            "name": "本地文件信息",
            "kind": "tool_call",
            "version": "1.0.0",
            "impl": "internal",
            "description": "查询白名单内文件或目录元信息。",
            "inputs": [
                {"name": "path", "type": "string", "required": True, "hint": "绝对路径"},
            ],
            "outputs": "type、size_bytes、modified_at JSON。",
        },
        {
            "id": "tool_local_file_delete",
            "name": "本地文件删除",
            "kind": "tool_call",
            "version": "1.1.0",
            "impl": "internal",
            "description": "删除文件；recursive=true 可删目录树。",
            "inputs": [
                {"name": "path", "type": "string", "required": True, "hint": "待删路径"},
                {"name": "recursive", "type": "bool", "required": False, "hint": "删非空目录"},
            ],
            "outputs": "deleted、type JSON。",
        },
    ]
